### DashBoard Data
GET http://localhost:3000/dashboard


### ResetPassword
POST http://localhost:3000/users/recover-pass
content-type: application/json

{
    "mail":"negove4884@hbehs.com"
}

### Password

POST http://localhost:3000/users/password

### TEST HASH Password

POST http://localhost:3000/users/test

### Logearse
POST http://localhost:3000/users/logIn
content-type: application/json

{
    "password": "123456",
    "username": "admin"
}

### Example JWT
GET http://localhost:3000/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwZXJzb25hX2lkIjp7Il9pZCI6IjYxZTkwMmQ4OTk2Y2M1N2I4ZGNhOTE4YSIsInBfY2VkdWxhIjoiMTMwNTQxMjMyMSIsInBfYXBlbGxpZG9zIjoiR29uemFsZXMgVmFzcXVleiIsInBfbm9tYnJlcyI6IlRpdHVzIEFsZXhhbmRlciIsIl9fdiI6MCwicF90ZWwiOiIwOTgzNDU2NTg1In0sInVfbWFpbCI6InRpdHVzYWxleEBob3RtYWlsLmNvbSIsInVfYWN0aXZvIjp0cnVlLCJ1X3VzdWFyaW8iOiJUaXR1c2d2Iiwicm9sX2lkIjp7Il9pZCI6IjYxZTdkYzIxYWVkNTkwMjczOTQ5OTYzZCIsInJfcm9sIjoiRW1wbGVhZG8iLCJfX3YiOjB9LCJzdWIiOiI2MWU5MDJkODk5NmNjNTdiOGRjYTkxOGQiLCJpYXQiOjE2NTMzNzM5MTQsImV4cCI6MTY1MzU0NjcxNH0.ej7foyMVsw_KfwP6PtlGNdIK7qKFCpG9FRqIjR3VF7I

### ROL

GET http://localhost:3000/rol/all

###

POST http://localhost:3000/rol/crear
content-type: application/json

{
    "r_rol": "Cliente"
}

### ------------ Persona -----------------
## CREAR
POST http://localhost:3000/persona/crear
content-type: application/json

{
    "p_nombres": "Renny",
    "p_apellidos":"Gorozabel Villavicencio",
    "p_cedula":"1305412421"
}
### BUSCAR

GET http://localhost:3000/persona/61e8f9c043a2dab293e11c88

### ELIMINAR

DELETE http://localhost:3000/persona/del/61ee3f1d8094d681eb1f6fd2

### ACTUALIZAR

PATCH  http://localhost:3000/persona/update/62e8f0ae0bdae22eb6ce19a7
content-type: application/json

{
    "p_nombres": "Renny Andrees",
    "p_apellidos":"Gorozabel Villavicencio"
}

### --------------USUARIOS---------
## CREAR
POST http://localhost:3000/users/crear
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwZXJzb25hX2lkIjp7Il9pZCI6IjYxZTkwMmQ4OTk2Y2M1N2I4ZGNhOTE4YSIsInBfY2VkdWxhIjoiMTMwNTQxMjMyMSIsInBfYXBlbGxpZG9zIjoiR29uemFsZXMgVmFzcXVleiIsInBfbm9tYnJlcyI6IlRpdHVzIEFsZXhhbmRlciIsIl9fdiI6MCwicF90ZWwiOiIwOTgzNDU2NTg1In0sInVfbWFpbCI6InRpdHVzYWxleEBob3RtYWlsLmNvbSIsInVfYWN0aXZvIjp0cnVlLCJ1X3VzdWFyaW8iOiJUaXR1c2d2Iiwicm9sX2lkIjp7Il9pZCI6IjYxZTdkYzIxYWVkNTkwMjczOTQ5OTYzZCIsInJfcm9sIjoiRW1wbGVhZG8iLCJfX3YiOjB9LCJzdWIiOiI2MWU5MDJkODk5NmNjNTdiOGRjYTkxOGQiLCJpYXQiOjE2NTU5MjMxNTEsImV4cCI6MTY1NjUyNzk1MX0.C_6QV03q8_k3i74dNtUHz6RfK00aw9JJ6Ul0U5RocD0
content-type: application/json

{
    "persona":
    {
        "p_nombres": "admin",
        "p_apellidos":"admin",
        "p_cedula":"1245132101"
    },
    "usuario":
    {
        "u_usuario":"admin",
        "u_mail":"rennygorozabel@gmail.com",
        "u_activo":true,
        "u_hash":"",
        "u_password":"",
        "rol_id":"61e7dc21aed590273949963d"
    },
    "rol":"EMPLEADO"
}

### LogIn
POST http://localhost:3000/users/log-cli
content-type: application/json

{
    "identificacion":"1305412421",
    "orden":"G2Y-1OL-FG4"
}

### ACTUALIZAR

PATCH  http://localhost:3000/users/update/61e902d8996cc57b8dca918d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwZXJzb25hX2lkIjp7Il9pZCI6IjYxZTkwMmQ4OTk2Y2M1N2I4ZGNhOTE4YSIsInBfY2VkdWxhIjoiMTMwNTQxMjMyMSIsInBfYXBlbGxpZG9zIjoiR29uemFsZXMgVmFzcXVleiIsInBfbm9tYnJlcyI6IlRpdHVzIEFsZXhhbmRlciIsIl9fdiI6MCwicF90ZWwiOiIwOTgzNDU2NTg1In0sInVfbWFpbCI6InRpdHVzYWxleEBob3RtYWlsLmNvbSIsInVfYWN0aXZvIjp0cnVlLCJ1X3VzdWFyaW8iOiJUaXR1c2d2Iiwicm9sX2lkIjp7Il9pZCI6IjYxZTdkYzIxYWVkNTkwMjczOTQ5OTYzZCIsInJfcm9sIjoiRW1wbGVhZG8iLCJfX3YiOjB9LCJzdWIiOiI2MWU5MDJkODk5NmNjNTdiOGRjYTkxOGQiLCJpYXQiOjE2NTU5MjMxNTEsImV4cCI6MTY1NjUyNzk1MX0.C_6QV03q8_k3i74dNtUHz6RfK00aw9JJ6Ul0U5RocD0
content-type: application/json

{
    "persona":
    {
        "p_nombres": "Tito Jose",
        "p_apellidos":"Gorozabel Villavicencio",
        "p_cedula":"1305412321",
        "p_tel":"0983456585"
    },
    "usuario":
    {
        "u_usuario":"TitusGV1",
        "u_mail":"titojoses@hotmail.com",
        "u_activo":true,
        "u_hash":"",
        "u_password":"12355",
        "rol_id":"61e7dc21aed590273949963d"
    }
}
###  CONSULTAR INFO

GET http://localhost:3000/users/61e902d8996cc57b8dca918d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwZXJzb25hX2lkIjp7Il9pZCI6IjYxZTkwMmQ4OTk2Y2M1N2I4ZGNhOTE4YSIsInBfY2VkdWxhIjoiMTMwNTQxMjMyMSIsInBfYXBlbGxpZG9zIjoiR29uemFsZXMgVmFzcXVleiIsInBfbm9tYnJlcyI6IlRpdHVzIEFsZXhhbmRlciIsIl9fdiI6MCwicF90ZWwiOiIwOTgzNDU2NTg1In0sInVfbWFpbCI6InRpdHVzYWxleEBob3RtYWlsLmNvbSIsInVfYWN0aXZvIjp0cnVlLCJ1X3VzdWFyaW8iOiJUaXR1c2d2Iiwicm9sX2lkIjp7Il9pZCI6IjYxZTdkYzIxYWVkNTkwMjczOTQ5OTYzZCIsInJfcm9sIjoiRW1wbGVhZG8iLCJfX3YiOjB9LCJzdWIiOiI2MWU5MDJkODk5NmNjNTdiOGRjYTkxOGQiLCJpYXQiOjE2NTU5MjMxNTEsImV4cCI6MTY1NjUyNzk1MX0.C_6QV03q8_k3i74dNtUHz6RfK00aw9JJ6Ul0U5RocD0

###  LISTAR

GET http://localhost:3000/users/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwZXJzb25hX2lkIjp7Il9pZCI6IjYyYmMxODFiYjJlMDJmYzJkYTkzY2NkZiIsInBfY2VkdWxhIjoiMTExMTExMTExIiwicF9hcGVsbGlkb3MiOiJhZG1pbiIsInBfbm9tYnJlcyI6ImFkbWluIiwiX192IjowfSwidV9tYWlsIjoicmVubnlnb3JvemFiZWxAZ21haWwuY29tIiwidV9hY3Rpdm8iOnRydWUsInVfdXN1YXJpbyI6ImFkbWluIiwicm9sX2lkIjp7Il9pZCI6IjYxZTdkNDA5YWVkNTkwMjczOTQ5OTYzYiIsInJfcm9sIjoiQWRtaW5pc3RyYWRvciIsIl9fdiI6MH0sInN1YiI6IjYyYmMxODFiYjJlMDJmYzJkYTkzY2NlMiIsImlhdCI6MTY1NzMzMjQ4MCwiZXhwIjoxNjU3OTM3MjgwfQ.u8D59IsdZ_UehPHcrf5kc1J7auC5Ber54qBjizAYAYY

### Password (Sin Has confirm)
POST http://localhost:3000/users/pass
content-type: application/json

{
    "user_id":"61e902d8996cc57b8dca918d",
    "pass":"1234"
}

### --- PEDIDOS LISTAR
POST http://localhost:3000/pedido/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwZXJzb25hX2lkIjp7Il9pZCI6IjYyYmMxODFiYjJlMDJmYzJkYTkzY2NkZiIsInBfY2VkdWxhIjoiMTExMTExMTExIiwicF9hcGVsbGlkb3MiOiJhZG1pbiIsInBfbm9tYnJlcyI6ImFkbWluIiwiX192IjowfSwidV9tYWlsIjoicmVubnlnb3JvemFiZWxAZ21haWwuY29tIiwidV9hY3Rpdm8iOnRydWUsInVfdXN1YXJpbyI6ImFkbWluIiwicm9sX2lkIjp7Il9pZCI6IjYxZTdkNDA5YWVkNTkwMjczOTQ5OTYzYiIsInJfcm9sIjoiQWRtaW5pc3RyYWRvciIsIl9fdiI6MH0sInN1YiI6IjYyYmMxODFiYjJlMDJmYzJkYTkzY2NlMiIsImlhdCI6MTY1NzMzMjQ4MCwiZXhwIjoxNjU3OTM3MjgwfQ.u8D59IsdZ_UehPHcrf5kc1J7auC5Ber54qBjizAYAYY
content-type: application/json



### Crear PEDIDO
POST http://localhost:3000/pedido/crear
content-type: application/json

{
    "pedido":
    {
        "ped_fc_registro":"2022-02-01T09:37:12.168Z",
        "ped_fc_fin":null
    },
    "id_usuario":"61e902d8996cc57b8dca918d"
}

### ACTUALIZAR PEDIDO
PATCH http://localhost:3000/pedido/update/624d49e60eb3e0a3bc28574e
content-type: application/json

{
    "pedido":
    {
        "ped_fc_registro":"2022-04-06T08:05:52.571Z",
        "ped_fc_fin":null,
        "ped_nro_orden" : "8O4-XSF-2J5",
        "ped_estado" : "CERRADO"
    }
}

### DELETE PEDIDO
DELETE http://localhost:3000/pedido/del/624d49e60eb3e0a3bc28574e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwZXJzb25hX2lkIjp7Il9pZCI6IjYxZTkwMmQ4OTk2Y2M1N2I4ZGNhOTE4YSIsInBfY2VkdWxhIjoiMTMwNTQxMjMyMSIsInBfYXBlbGxpZG9zIjoiR29yb3phYmVsIFZpbGxhdmljZW5jaW8iLCJwX25vbWJyZXMiOiJUaXRvIEpvc2UiLCJfX3YiOjAsInBfdGVsIjoiMDk4MzQ1NjU4NSJ9LCJ1X21haWwiOiJ0aXRvam9zZXNAaG90bWFpbC5jb20iLCJ1X2FjdGl2byI6dHJ1ZSwidV91c3VhcmlvIjoiVGl0dXNndjIiLCJyb2xfaWQiOnsiX2lkIjoiNjFlN2RjMjFhZWQ1OTAyNzM5NDk5NjNkIiwicl9yb2wiOiJFbXBsZWFkbyIsIl9fdiI6MH0sInN1YiI6IjYxZTkwMmQ4OTk2Y2M1N2I4ZGNhOTE4ZCIsImlhdCI6MTY2MjU4MDA5OSwiZXhwIjoxNjYzMTg0ODk5fQ.8Y9Z2Z-BmC9Sc2Xei8onZ3PjuAdkDtZwj1CLY9yuw0Y

### LISTAR TICKETS
GET http://localhost:3000/ticket/all/624d49e60eb3e0a3bc28574e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwZXJzb25hX2lkIjp7Il9pZCI6IjYxZTkwMmQ4OTk2Y2M1N2I4ZGNhOTE4YSIsInBfY2VkdWxhIjoiMTMwNTQxMjMyMSIsInBfYXBlbGxpZG9zIjoiR29yb3phYmVsIFZpbGxhdmljZW5jaW8iLCJwX25vbWJyZXMiOiJUaXRvIEpvc2UiLCJfX3YiOjAsInBfdGVsIjoiMDk4MzQ1NjU4NSJ9LCJ1X21haWwiOiJ0aXRvam9zZXNAaG90bWFpbC5jb20iLCJ1X2FjdGl2byI6dHJ1ZSwidV91c3VhcmlvIjoiVGl0dXNndjIiLCJyb2xfaWQiOnsiX2lkIjoiNjFlN2RjMjFhZWQ1OTAyNzM5NDk5NjNkIiwicl9yb2wiOiJFbXBsZWFkbyIsIl9fdiI6MH0sInN1YiI6IjYxZTkwMmQ4OTk2Y2M1N2I4ZGNhOTE4ZCIsImlhdCI6MTY2MjU4MDA5OSwiZXhwIjoxNjYzMTg0ODk5fQ.8Y9Z2Z-BmC9Sc2Xei8onZ3PjuAdkDtZwj1CLY9yuw0Y




### CREAR TICKET
POST http://localhost:3000/ticket/crear
content-type: application/json

{
    "ticket":
    {
        "t_detalle":"PRUEBA 21",
        "t_total":11,
        "t_abono":5,
        "t_tipo_equipo":"COMPUTADOR"
    },
    "id_pedido":"61f900151c56deb4b891b893"
}

### ACTUALIZAR TICKET
PATCH http://localhost:3000/ticket/update/61f900151c56deb4b891b893
content-type: application/json

{
    "ticket":
    {
        "t_detalle":"NO ENCIENDE, PANTALLA ROTISIMA",
        "t_saldo":0,
        "t_num":"ox4-bc2-9jk",
        "t_abono":0,
        "t_tipo_equipo":"COMPUTADOR"
    }
}

### ------------ ESTADOS CREAR
POST http://localhost:3000/estado/crear
content-type: application/json

{
    "estado":{
        "e_nombre":"COMPLETO",
        "e_detalle":"Listo para entrega",
        "e_usuario":"Juan Segundo",
        "user_id": {
            "persona_id": "61e902d8996cc57b8dca918a",
            "u_activo": true,
            "u_mail": "titojoses@hotmail.com",
            "u_usuario": "TitoGV",
            "_id": "61e902d8996cc57b8dca918d"
            }
    },
    "id_ticket":"62395dc0497153b3cfb10b6b"
}

### UPDATE ESTADO
PATCH http://localhost:3000/estado/update/623a4863ec10d1bb34a2a93d
content-type: application/json

{
    "comentario":{
        "c_detalle":"Mas comentarios",
        "c_usuario":"TitoGV",
        "user_id": "61e902d8996cc57b8dca918d"
    }
}


### LISTAR
GET http://localhost:3000/estado/all/624d49ef0eb3e0a3bc285762



### LISTAR
GET http://localhost:3000/estado/allLast/6238cacc287d5b3d5dcaa20a

### Comentarios

GET http://localhost:3000/estado/comentarios/623a4863ec10d1bb34a2a93d

### ##### NOTIFICACIONES

###
GET http://localhost:3000/noti/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwZXJzb25hX2lkIjp7Il9pZCI6IjYxZTkwMmQ4OTk2Y2M1N2I4ZGNhOTE4YSIsInBfY2VkdWxhIjoiMTMwNTQxMjMyMSIsInBfYXBlbGxpZG9zIjoiR29uemFsZXMgVmFzcXVleiIsInBfbm9tYnJlcyI6IlRpdHVzIEFsZXhhbmRlciIsIl9fdiI6MCwicF90ZWwiOiIwOTgzNDU2NTg1In0sInVfbWFpbCI6InRpdHVzYWxleEBob3RtYWlsLmNvbSIsInVfYWN0aXZvIjp0cnVlLCJ1X3VzdWFyaW8iOiJUaXR1c2d2Iiwicm9sX2lkIjp7Il9pZCI6IjYxZTdkYzIxYWVkNTkwMjczOTQ5OTYzZCIsInJfcm9sIjoiRW1wbGVhZG8iLCJfX3YiOjB9LCJzdWIiOiI2MWU5MDJkODk5NmNjNTdiOGRjYTkxOGQiLCJpYXQiOjE2NTMzNzYxODQsImV4cCI6MTY1MzU0ODk4NH0.Ed6jF2-tZJe_byauY-fdHul4pGnVwnst8sWK6vl5hR8

###
GET http://localhost:3000/noti/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWVlNDAzNjgwOTRkNjgxZWIxZjZmZGMiLCJwZXJzb25hX2lkIjp7Il9pZCI6IjYxZWU0MDM2ODA5NGQ2ODFlYjFmNmZkOSIsInBfY2VkdWxhIjoiMTMwNTQxMjQyMSIsInBfYXBlbGxpZG9zIjoiR29uemFsZXMgVmFycXVleiIsInBfbm9tYnJlcyI6IlJlbm8iLCJfX3YiOjB9LCJ1X21haWwiOiJyZW5vZ29uQGhvdG1haWwuY29tIiwidV9hY3Rpdm8iOnRydWUsInVfdXN1YXJpbyI6IlJHViIsInJvbF9pZCI6eyJfaWQiOiI2MWU3ZGMyN2FlZDU5MDI3Mzk0OTk2M2YiLCJyX3JvbCI6IkNsaWVudGUiLCJfX3YiOjB9LCJzdWIiOiI2MWVlNDAzNjgwOTRkNjgxZWIxZjZmZGMiLCJpYXQiOjE2NTMzNzYyMDIsImV4cCI6MTY1MzU0OTAwMn0.C8OzTNANaQKDb4v8WqkVPhVxz9YDODwKtGe036pi-os

### Crear Admin (Dev)
POST https://systec-backend.herokuapp.com/users/postPlan
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwZXJzb25hX2lkIjp7Il9pZCI6IjYyODQ4MzQyOGU1ZjMwNmMyNGM1ZjM1YSIsInBfY2VkdWxhIjoiMTI0NTEzMjEwMSIsInBfYXBlbGxpZG9zIjoiYWRtaW4iLCJwX25vbWJyZXMiOiJhZG1pbiIsIl9fdiI6MH0sInVfbWFpbCI6InJlbm55Z29yb3phYmVsQGdtYWlsLmNvbSIsInVfYWN0aXZvIjp0cnVlLCJ1X3VzdWFyaW8iOiJhZG1pbiIsInJvbF9pZCI6eyJfaWQiOiI2MWU3ZGMyMWFlZDU5MDI3Mzk0OTk2M2QiLCJyX3JvbCI6IkVtcGxlYWRvIiwiX192IjowfSwic3ViIjoiNjI4NDgzNDI4ZTVmMzA2YzI0YzVmMzVkIiwiaWF0IjoxNjU2NDk3ODE3LCJleHAiOjE2NTcxMDI2MTd9.PRd6pweRjeoge01hi9cIjI0uTY84NN6WFlPHjAYw_FM
content-type: application/json

{
    "persona":
    {
        "p_nombres": "adm",
        "p_apellidos":"adm",
        "p_cedula":"111111111"
    },
    "usuario":
    {
        "u_usuario":"adm",
        "u_mail":"ragvdr4develop@gmail.com",
        "u_activo":true,
        "u_hash":"",
        "u_password":"",
        "rol_id":"61e7dc21aed590273949963d"
    }
}